### ISSUE TITLE
Arguably use of $watch

### ISSUE THREAD

**Issue by dupuchba** [mikecrittenden/toogles#11]
First of all, nice work guys.

***
But, I am not quite sure that the use of $watch in list.js is the easiest way to do that as it is a best practice to not call it in controllers. [blog post here](http://www.benlesh.com/2013/08/angularjs-watch-digest-and-apply-oh-my.html)

What about calling search in the ng-submit function of list.html and then set the location ?

**Comment by mikecrittenden** [comment]
Closing this because it's old and I'm too lazy to work on it at this point.

**Comment by dupuchba** [comment]
That's a great answer lol :8ball:
