### ISSUE TITLE
touch and css problems on mobile

### ISSUE THREAD

**Issue by vanderleisp** [mikecrittenden/toogles#18]
While testing the demo file on browser it didn't work (running it via a local server or also using the Firefox Developer browser), like as the side menu for the search (not on the initial screen with pre-programmed name but doing a new word search) were going all the way to the right side of screen, so while trying to select one of the videos the selection was being done for the Options in the search menu instead.
Using the browser's developer tools I could find out that the main.scss file was the one causing the problem so I went to the toogl.es web site and downloaded the main.css file from there, and its running perfectly now.

Now the problem is that for the mobile application I'm still using the Titanium cross-developer tool, as a webview, and there it's also now running well the whole app BUT the touch is difficult, like to select any of the videos.
I've already took out the fastclick.js, as maybe it was in conflict with either the angular-touch.js or the own Titanium touch access, but either taking one or the other out didn't fix the problem and it's still hard to select any video.
Any help on this ?

One last point is that the foundation framework has compatibility with Android 4.2+ only, so as still there are lots of devices with older versions then could be a problem while deploying app.

**Comment by mikecrittenden** [comment]
Not sure why it would be difficult on mobile -- I haven't messed with that
at all so unfortunately I won't be any support there.

**Comment by vanderleisp** [comment]
somehow it's difficult to select any video only when you do a search for a different name instead of on initial page that shows videos based on original one that you used.
I've seem some comments on internet about problems with fastclick and angular-touch, but as I took both out of this test (and also took out aria...) then still couldn't figure out where the problem is.
It works, but for a user perspective then could become a big issue later.
