### ISSUE TITLE
Liking/Disliking

### ISSUE THREAD

**Issue by SumOfAllN00bs** [mikecrittenden/toogles#22]
Is liking or disliking a video possible or is that functionality only available from YouTube itself

**Comment by mikecrittenden** [comment]
Only available on YouTube itself. Toogles can't do it because it doesn't know anything about your YouTube account (you don't sign into Toogles), and the embedded player doesn't support it (see https://productforums.google.com/forum/#!topic/youtube/eFhkYOJDicA).

**Comment by SumOfAllN00bs** [comment]
​
